---
  version: 1
  schedule:
    type: "simple"
    interval: "5s"
  max-failures: 10
  workflow:
    collect:
      config:
      metrics:
        /intel/psutil/load/load1: {} 
        /intel/psutil/load/load15: {}
        /intel/psutil/load/load5: {}
        /intel/psutil/vm/available: {}
        /intel/psutil/vm/free: {}
        /intel/psutil/vm/used: {}
      publish:
        - plugin_name: "awssqs"
          config:
            debug_file: "/tmp/awssqs-debug.log"
            akid: "1234ABCD"
            secret: "1234ABCD"
            queue: "https://sqs.us-east-1.amazonaws.com/208379614050/sqs_demo"
